### ISSUE TITLE
Unknown runtime specified nvidia (using CPU)

### ISSUE THREAD

**Issue by Rzfeng** [UW-COSMOS/Cosmos#40]
```
Starting cosmos_redis_1           ... done
ERROR: for cosmos_cosmos_1  Cannot create container for service cosmos: Unknown runtime specified nvidia

ERROR: for cosmos  Cannot create container for service cosmos: Unknown runtime specified nvidia
ERROR: Encountered errors while bringing up the project.
```

When trying to create and start the docker-compose.yml container and you encounter this error, the docker-compose.yml needs to be modified.

Comment out line 5 (runtime: nvidia) to fix the error and use the default runtime option
```
  1 version: "2.3"
  2 services:
  3     cosmos:
  4         build: .
  5         runtime: nvidia
  6         ipc: host
  7         volumes:
  8             - .:/cosmos/
  9             - ${INPUT_DIR}:/input/
 10             - ${OUTPUT_DIR}:/output/
 11         command: "python run.py /input  -w torch_model/model_weights.pth -t 4 -o /output/ -d ${DEVICE} -k"
```

**Comment by Rzfeng** [comment]
After fixing this error, another issue persists when building the model (still unsolved)

```
3c433cce2c59_cosmos_cosmos_1 | ===== BUILDING MODEL ======
3c433cce2c59_cosmos_cosmos_1 | Built backbone resnet50
3c433cce2c59_cosmos_cosmos_1 | Building downstream components via shape testing
3c433cce2c59_cosmos_cosmos_1 | done shape testing, building, attention mechanisms
3c433cce2c59_cosmos_cosmos_1 | built multi head attention
3c433cce2c59_cosmos_cosmos_1 | 8, 8, 2048
3c433cce2c59_cosmos_cosmos_1 | super called
3c433cce2c59_cosmos_cosmos_1 | going to build a 131072 by 1024 matrix of weights
3c433cce2c59_cosmos_cosmos_1 | built embeddings
3c433cce2c59_cosmos_cosmos_1 | done
3c433cce2c59_cosmos_cosmos_1 | Traceback (most recent call last):
3c433cce2c59_cosmos_cosmos_1 |   File "run.py", line 132, in <module>
3c433cce2c59_cosmos_cosmos_1 |     run_inference(f'{tmp}/images', f'{tmp}/cc_proposals', model_config, weights, xml, device)
3c433cce2c59_cosmos_cosmos_1 |   File "/app/infer/infer.py", line 23, in run_inference
3c433cce2c59_cosmos_cosmos_1 |     model.load_state_dict(torch.load(weights, map_location={"cuda:0": device_str}))
3c433cce2c59_cosmos_cosmos_1 |   File "/home/user/.local/lib/python3.6/site-packages/torch/serialization.py", line 358, in load
3c433cce2c59_cosmos_cosmos_1 |     return _load(f, map_location, pickle_module)
3c433cce2c59_cosmos_cosmos_1 |   File "/home/user/.local/lib/python3.6/site-packages/torch/serialization.py", line 532, in _load
3c433cce2c59_cosmos_cosmos_1 |     magic_number = pickle_module.load(f)
3c433cce2c59_cosmos_cosmos_1 | _pickle.UnpicklingError: invalid load key, 'v'.
3c433cce2c59_cosmos_cosmos_1 exited with code 1
```

**Comment by outdamud** [comment]
https://cryptojedi.org/peter/data/pairing-20131122.pdf
Maybe this will help

**Comment by ankur-gos** [comment]
Stale, closing.
